# Generated by Django 5.0.6 on 2024-06-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourseprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentCourseProgress',
        ),
    ]
